<?

//MOVE A SINGLE CUSTOMER'S LOAD DATA
function domainLoadUpdate($cdrConn, $utilConn, $new, $client) {
	//Requires connections to the util database and to the cdr server database
	//prev is the ip address of the server that previously hosted the client
	//new is the ip address of the server that now hosts the client
	//client is the uuid of the customer that was moved
	
	//Find out which server had load data for this client
	$thisPrev = pg_fetch_result(pg_query($cdrConn, "SELECT assigned_server FROM loadmetrics WHERE id = '$client'"), 0);

	//Change the server this client is assigned to and get the total load generated by this client
	$thisLoad = pg_fetch_result(pg_query($cdrConn, "UPDATE loadmetrics SET assigned_server = '$new' WHERE id = '$client' RETURNING load_in + load_out + load_custom;"), 0);

//	echo "DEBUG: $thisPrev, $thisLoad, $new, $client ";
	//pg_fetch_result returns false on errors. 
	if (!$thisPrev || !$thisLoad) {
		//if the $thisLoad is an integer, then the query returned 0, otherwise, the query returned false.  
		if (gettype($thisLoad == 'integer')) {
			return true;
		}
	return false;
	}

	//Make sure our queries are ready for pg_query
	$thisLoad = intval($thisLoad);
	$subtract = "UPDATE pbxstatus SET load = load - $thisLoad WHERE ip = '$thisPrev'";
	$add = "UPDATE pbxstatus SET load = load + $thisLoad WHERE ip = '$new'";

//	echo "DEBUG: $first, $second ";
	//Subtract load from the previous server, add it to the new one
	$first = pg_query($utilConn, $subtract);
	$second = pg_query($utilConn, $add);

	//pg_query returns false on error
	if (!$first || !$second) {
		return false;
	}
	
	return true;
}

//MOVE ALL THE LOAD DATA FROM ONE SERVER TO ANOTHER
function serverLoadUpdate($cdrConn, $utilConn, $old, $new) {
	//Requires connections to cdr and util databases
	//old is the server that everyone was moved from
	//new is the server everyone was moved to

	//Update server addresses for each client, and get a sum of all load moved
	$thisLoad = pg_fetch_result(pg_query($cdrConn, "SELECT SUM(load_in + load_out + load_custom) FROM loadmetrics WHERE assigned_server = '$old'"), 0); 
	$thisUpdate = pg_query($cdrConn, "UPDATE loadmetrics SET assigned_server = '$new' WHERE assigned_server = '$old'");

	//Catch errors
	if (!$thisLoad || !$thisUpdate) {
		return false;
	}

	$thisLoad = intval($thisLoad);
	$subtract = "UPDATE pbxstatus SET load = 0 WHERE ip = '$old'";
	$add = "UPDATE pbxstatus SET load = load + $thisLoad WHERE ip = '$new'";

	//Subtract load from the previous server, add it to the new one
	$first = pg_query($utilConn, $subtract);
	$second = pg_query($utilConn, $add);

	//pg_query returns false on error
	if (!$first || !$second) {
		return false;
	}
	
	return true;
}

?>
